// Package scaffold implements `frostfall init`: detect the frontend project's
// shape and generate a tailored starter config, so any project gets from zero
// to a first scan without reading the schema docs.
package scaffold

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
)

// Project is what detection learned from the target directory.
type Project struct {
	Framework  string // vite | next | cra | sveltekit | astro | static | unknown
	Runner     string // yarn | pnpm | npm
	DevCommand string
	Port       int
	BuildDir   string // relative build output dir, "" if unknown
}

type packageJSON struct {
	Scripts         map[string]string `json:"scripts"`
	Dependencies    map[string]string `json:"dependencies"`
	DevDependencies map[string]string `json:"devDependencies"`
}

// Detect inspects dir for lockfiles, package.json deps, and build output.
func Detect(dir string) Project {
	p := Project{Framework: "unknown", Runner: "npm"}

	if exists(filepath.Join(dir, "yarn.lock")) {
		p.Runner = "yarn"
	} else if exists(filepath.Join(dir, "pnpm-lock.yaml")) {
		p.Runner = "pnpm"
	}

	raw, err := os.ReadFile(filepath.Join(dir, "package.json"))
	if err != nil {
		if exists(filepath.Join(dir, "index.html")) {
			p.Framework = "static"
			p.BuildDir = "."
		}
		return p
	}
	var pkg packageJSON
	if err := json.Unmarshal(raw, &pkg); err != nil {
		return p
	}

	dep := func(name string) bool {
		_, a := pkg.Dependencies[name]
		_, b := pkg.DevDependencies[name]
		return a || b
	}

	switch {
	case dep("next"):
		p.Framework = "next"
		p.Port = 3000
		p.BuildDir = "out" // static export; server output needs spawn mode
	case dep("@sveltejs/kit"):
		p.Framework = "sveltekit"
		p.Port = 5173
		p.BuildDir = "build"
	case dep("astro"):
		p.Framework = "astro"
		p.Port = 4321
		p.BuildDir = "dist"
	case dep("vite"):
		p.Framework = "vite"
		p.Port = 5173
		p.BuildDir = "dist"
	case dep("react-scripts"):
		p.Framework = "cra"
		p.Port = 3000
		p.BuildDir = "build"
	}

	p.DevCommand = devCommand(p.Runner, pkg.Scripts)
	return p
}

func devCommand(runner string, scripts map[string]string) string {
	for _, name := range []string{"dev", "start"} {
		if _, ok := scripts[name]; ok {
			if runner == "npm" {
				return "npm run " + name
			}
			return runner + " " + name
		}
	}
	return ""
}

func exists(path string) bool {
	_, err := os.Stat(path)
	return err == nil
}

// Render produces the starter .frostfall.yml for a detected project.
func Render(p Project) string {
	server := "server:\n"
	switch {
	case p.BuildDir != "" && p.Framework != "unknown":
		server += fmt.Sprintf("  # Scan the production build (recommended for CI): dev builds carry\n"+
			"  # dev-only DOM that can produce phantom violations.\n"+
			"  serve: %s\n", p.BuildDir)
		if p.DevCommand != "" {
			server += fmt.Sprintf("  # Or have frostfall start the dev server itself:\n"+
				"  # command: %s\n  # port: %d\n", p.DevCommand, p.Port)
		}
	case p.DevCommand != "":
		server += fmt.Sprintf("  command: %s\n  port: %d\n", p.DevCommand, p.Port)
	default:
		server += "  # Point at your running app, e.g.:\n  baseUrl: http://localhost:3000\n"
	}

	buildDir := p.BuildDir
	if buildDir == "" {
		buildDir = "./dist"
	}
	return fmt.Sprintf(`version: 1

# Generated by frostfall init (detected: %s). Adjust and commit.
# Docs: https://github.com/aquia-inc/frostfall

%s
defaults:
  standard: wcag21aa        # or wcag22aa, section508, best-practice
  # By default frostfall REPORTS violations without failing the build.
  # Uncomment expect: to enforce — fail CI on new violations:
  # expect:
  #   severity: serious     # fail at this impact or worse
  #   rules: [image-alt]    # and/or fail on specific rules at any impact

# On first run, accept existing violations so only NEW ones fail the build:
#   frostfall --update-baseline
baseline: .frostfall-baseline.json

# Environment overlays. "ci" applies automatically in GitHub Actions.
# Profiles may override server/defaults/baseline/discover - never tests.
# profiles:
#   ci:
#     server:
#       serve: %s
#     defaults:
#       expect:
#         severity: serious

tests:
  - id: home
    path: /

  # Accessibility bugs live in states, not pages — scan modals, menus, and
  # forms after interaction:
  # - id: example-modal
  #   path: /
  #   steps:
  #     - click: "#open-modal"
  #     - waitFor: "[role=dialog]"
  #     - scan:
  #         label: modal-open
  #         scope: "[role=dialog]"
`, p.Framework, server, buildDir)
}
